# Generated by Django 5.1.1 on 2024-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Category not specified', max_length=150),
            preserve_default=False,
        ),
    ]
